### PR TITLE
Remove the need for yarn

### PR DESCRIPTION
**Pull request by akkesm**
The package is built from the appimage instead of from source with yarn2nix.

### CODE REVIEW

**Comment by akkesm** [comment]
PS: flake.nix contains a list of supported platforms, it is possible to add more. See the full list [in nixpkgs here](https://github.com/NixOS/nixpkgs/blob/master/lib/systems/doubles.nix).

**Comment by zigazajc007** [comment]
I never used Nix OS, so I don't have any experience here.
I'm just checking if this code contains anything malicious.

**Comment by akkesm** [comment]
Yeah that's fair, I'm just saying if you intend to package it for Darwin, Nix is a way to do so. You can install Nix on any unix system, I'm using it on Fedora.

**Comment by zigazajc007** [comment]
The problem is that I don't own any Apple product. So I can't compile desktop application for Mac OS and can't start working on Iphone application. I will try my best to get Apple products.

**Pull request merged**
